### ISSUE TITLE
addition of data cursor to graph view

### ISSUE THREAD

**Issue by midnightcoup** [creepymonster/GlucoseDirect#131]
It is currently not possible in graph view to have a data cursor to see what the blood glucose value is at a specific time on the graph. Sure, this can be seen by scrolling on the table view but a data cursor implementation on the graph would be a lot more usable.

xDrip has a very nice implementation of this.

**Comment by creepymonster** [comment]
This feature was added for iOS 16 devices - so I close the ticket :)
