### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by egpall** [creepymonster/GlucoseDirect#322]
Ayer instalé iOS 16 beta 4 y GlucoseDirect crash

**Comment by egpall** [comment]
He vuelto a la versión anterior de GlucoseDirect y no crash

**Comment by creepymonster** [comment]
Which version did you have installed? I had published the 1.0.0 (102) via TestFlight yesterday, which works for me with the iOS 16 beta.

This morning I had already received feedback that the latest TestFlight version no longer crashes after a reboot of the phone under iOS 16.

Many greetings
Reimar

**Comment by egpall** [comment]
Después de instalar la 1.0.0 hacía crash, apagué el teléfono y seguía igual, voy ahora a meterla de nuevo y a resetear el teléfono. Muchas gracias.

**Comment by egpall** [comment]
He instalado la 1.0.0 y reseteado el iPhone con iOS 16 beta 4 y sigue crash, no puedo enviar la BD porque no hace crash

**Comment by creepymonster** [comment]
Unfortunately, I have no clue yet what has changed that can lead to problems in places.

I will try to find out more from the crash reports.

Many greetings
Reimar

**Comment by egpall** [comment]
Gracias. Magnífica App.

**Comment by egpall** [comment]
Voy a cambiar a idioma inglés, a ver si se soluciona

**Comment by egpall** [comment]
Sigue igual con idioma inglés

**Comment by egpall** [comment]
He reiniciado también

**Comment by creepymonster** [comment]
I'm afraid I'm going to have to fumble my way a bit. I have created a new build (105).

Should the build start for you it would be great if you could send me your DB under settings.

Many greetings
Reimar

**Comment by egpall** [comment]
Cuando me salga en TestFlight la instalo y te envío la BD, todavía me sale la 100.

**Comment by creepymonster** [comment]
Which is the latest version you can install via TestFlight - do you already see versions 102, or later?

**Comment by egpall** [comment]
Acabo de instalar la 102 y ya funciona bien!!!! No crash!!!!! Gracias

**Comment by creepymonster** [comment]
That's good ☺️, then I had a thinking error at noon today 😁.

I thought you are in the iOS 16 test group and already have access to build 102, but you are registered normally via TestFlight and could not yet get the latest update.

Until now, it was always necessary to rebuild the app once with a new beta.

**Comment by egpall** [comment]
Sí, soy un usuario normal a través de TestFlight
