### ISSUE TITLE
Suggestion integration Calendar

### ISSUE THREAD

**Issue by egpall** [creepymonster/GlucoseDirect#352]
The integration with Calendar seems magic to me, it is wonderful, even in CarPlay it gives me the current values, but I have a suggestion, the highest refresh time is 15 minutes and in Calendar the values for 10 minutes appear so there are 5 minutes in which there is no data, if the times coincided there would be no times in Calendar without values. Could it be done? Thank you

**Comment by creepymonster** [comment]
I do not know yet if I understand the problem correctly.

The app itself updates the calendar every minute - every minute the calendar entry is updated. So you can always see the latest values on the Apple Watch, for example.

Is there a limit in Car? Or where do the 10/15 minutes come from? And how can I imagine that the gaps arise?

**Comment by egpall** [comment]
I have said about CarPlay only as a compliment, I add 2 photos where you can see that my calendar assigns 10 minutes to each event and as I refresh the value in GlucoseDirect every 15 minutes there are 5 minutes without values. Why do you create the 10-minute calendar events for me? Have you programmed that time or is it my iPhone? Thank you again

![045018BB-3175-43C5-813C-326DAEF70A02](https://user-images.githubusercontent.com/61494891/183249869-1a503314-1adf-40bb-a5dc-2bf8d4713cfb.png)
![2BCC1223-1116-4CDF-8D41-63B5C5CF8CBB](https://user-images.githubusercontent.com/61494891/183249871-002ae56f-bd27-4735-86ea-dd8e8d689755.png)

**Comment by creepymonster** [comment]
Ah, I see - the 10 minutes displayed there are just the length of the calendar entry. This does not create any gaps.

An entry in the calendar must have a start and end time - I have only selected 10 minutes there. The actual length of the entry has no meaning.

Even if you set the interval to 1 minute, the calendar entries have a length of 10 minutes.

I will adjust it so that the length of the entry corresponds to the interval of the sensor.

**Comment by egpall** [comment]
Perfect!!!!!! Thank you again

**Comment by creepymonster** [comment]
I have made the adjustment - with the next update the length of the calendar entry corresponds to the sensor interval.

Many greetings
Reimar

**Comment by egpall** [comment]
Perfect. Thank you very much.

**Comment by egpall** [comment]
Sigo teniendo tiempos sin valores en Calendario, creo que se solucionaría si para el intervalo de 1’ en Calendario fueran 2’, para 5’ fueran 8’ y para 15’ por ejemplo 20’. Es sólo una sugerencia.
