### ISSUE TITLE
[Feature Request] Export data to a webhook

### ISSUE THREAD

**Issue by mawasile** [creepymonster/GlucoseDirect#380]
Hi 

Would you consider added calling a settings configured webhook on top of Apple Health, NightScout export? 
Data would be sent in json format with the same interval as "Retrieval Interval" for sensor scanning. 

That would enable interacting with data like for example integration with Amazon Alexa etc.

**Comment by creepymonster** [comment]
Hello,

sorry that I answer only now - I was on the road the last few days.

I can definitely imagine that with the webhook. Interested parties (who compile the source code themselves) could also add it relatively easily (similar to the Nightscout integration) themselves.

This way, IFTTT could be connected as well, for example. I'll have a look at the whole topic - I don't have much experience with Alexa - but the example of IFTTT makes it easier for me.

Many greetings
Reimar
