### ISSUE TITLE
The Libre 3 serial number should be only 9 chars long.

### ISSUE THREAD

**Issue by gui-dos** [creepymonster/GlucoseDirect#420]
LibreLinkUp is storing the serial numbers of the active sensors using 10 chars. For the Libre 1 and 2 you have to prepend their product family codes `0` and `3` and in the case of the Libre 3 you have to drop the final `0`.

![serail10chars](https://user-images.githubusercontent.com/7220550/201052858-fede5f21-e79e-46f0-84ca-841094965072.png)

**Comment by creepymonster** [comment]
You are right, thank you very much - I will correct that.

**Comment by creepymonster** [comment]
With the last version I have corrected the serial number.

Thank you gui-dos
