### ISSUE TITLE
Kennzeichensymbol verschwindet

### ISSUE THREAD

**Issue by FriedelXT** [creepymonster/GlucoseDirect#423]
Hallo,

das kennzeichensymbol wird nicht zuverlässig angezeigt.
Mal ist es da, mal nicht.

aktuelle GlucoseDirect version

Schöne Grüsse
Friedhelm Walldorf

**Comment by creepymonster** [comment]
Hallo,

um die Anzeige des Glukosewertes auf dem App Symbol auf für mmol Werte zu ermöglichen, gibt es nur die Möglichkeit iOS Benachrichtigungen zu nutzen.

Auf diesem Weg können mmol Werte angezeigt werden.

Wenn man jetzt aber zum Beispiel die normalen Glukose Benachrichtigungen ausstellt, erscheint der Glukosewert auf dem App Symbol nur noch wenn man zu hoch ist.

Hast du eventuell eine der folgenden Benachrichtigungen deaktiviert?

![FF7E9731-25AD-4A11-9DB5-31AFEAFE2D22](https://user-images.githubusercontent.com/5388815/202006646-ac4dbe78-a693-463b-b861-096ab694c8e2.jpeg)

Viele Grüße 
Reimar

**Comment by FriedelXT** [comment]
Hi Reimar,

genau das wars. Da bin ich Depp gar nicht drauf gekommen, weil ich an Alarm gedacht habe.
Danke für den Hinweis.

Schöne Grüsse
Friedhelm

**Comment by creepymonster** [comment]
Leider ist Apple da nicht sehr konsequent - mit der einen Methode sind nur ganze Zahlen möglich, mit der anderen sowohl als auch.

Ich wollte das GD sich bei mmol und mg/dl Werten gleich verhält.

Da es wichtig war die Benachrichtigungen für normale Werte auszustellen (es gibt SmartWatches die ansonsten bei jedem Wert vibrieren) gab es nur die Möglichkeit in diesem Fall die Werte von dem Icon zu löschen. Ein veralteter Wert wäre auch nicht hilfreich.

So erschien es mir als der Beste Kompromiss 

Viele Grüße 
Reimar
