### ISSUE TITLE
"0 hours left" notification when sensor has 24 hours remaining. 

### ISSUE THREAD

**Issue by t1mlopez** [creepymonster/GlucoseDirect#427]
Using Libre 3 (US) with LIbreLinkUp configured, when I hit the 24 hour left mark on my sensor, I received a notification warning me there were "0 hours" left. Unfortunately, I selected the alert so it was removed from my notification center and I couldn't get a screenshot. 

[Logs.txt]
deleted - please do not post logs and rather email me.

**Comment by creepymonster** [comment]
Thanks for the tip, I will take a closer look at the problem.

**Comment by creepymonster** [comment]
There was an error in the display of notifications, which led to the fact that (with less than 24 hours) the remaining hours and minutes were not displayed. I am currently testing a fix, which I will publish with the next release.
