### ISSUE TITLE
LibreLinkUp with Libre3

### ISSUE THREAD

**Issue by Rtzftz** [creepymonster/GlucoseDirect#428]
I like the idea that the GlucoseDirect can directly get its data from LibreLinkUp for Libre3 users.
This feature appears after scanning a Libre3 sensor and also some basic information are shown... nice.
But why is a bluetooth connection needed? The data will be collected by the Libre3 App also via bluetooth an it seems that both apps interfere with each other due to both have bluetooth enabled. The result is that either the Libre3 App or GlucoseDirect losts the connection and no data is collected/shown.

![IMG_A918D0C29374-1](https://user-images.githubusercontent.com/118640228/203985921-40f81839-6afa-4682-88cb-3638d4b50cbb.jpeg)

**Comment by creepymonster** [comment]
Hello,

unlike the Libre 2, it is not a problem here at the moment that both apps use Bluetooth. The apps do not get in each other's way here.

With the Libre 3, I only use the Bluetooth connection of the sensor, but not the data that flows there. So there is no need to worry about iOS closing the app in the background and waking up every minute when the sensor sends data.

If the connection is disconnected, there is an error message at the bottom. As a rule, the connection is then automatically re-established.

Many greetings
Reimar
