### ISSUE TITLE
More Alarm Options

### ISSUE THREAD

**Issue by Rtzftz** [creepymonster/GlucoseDirect#429]
It would be great to have more alarm options:
High/Low @ XX mg/dl = Sound but no "override mute"
Very High/Low @ YY mg/dl = Sound and "override mute"

From my opinion this is very good implemented in xdrip4ios where alarm types an treshholds can be customized and combined completely free.

In combination with this it would be nice to have a "targe bg zone" (e.g. 80-180) and additional "lines" for high/low and very high/low. At the moment the graph only shows, that you are somewhere between "high" and "low".

**Comment by creepymonster** [comment]
Thank you for your feedback.

I must admit that the alarm options in xDrip4iOS were always a bit too detailed for me.

For me, High/Very High (or Low/Very Low) always had the same value and the same need for action.

Your suggestion with Target Zone and red areas for Very High/Low I find but very good and I will quickly implement.

I have long on my todo to revise the alarm system.
