### ISSUE TITLE
Trying to install direct glucose in testflight

### ISSUE THREAD

**Issue by myanezpagans** [creepymonster/GlucoseDirect#435]
Hi!

I am trying to install direct glucose in testflight but I am being asked for a redeem code that I am not sure where I can get. I am a Libre 3 user based in the USA and I am trying to link my data to nightscout using direct glucose. From reading many pieces of information it seems that your app will help me achieve this objective. But I am not very tech savvy so I have been struggling trying to understand how things work. Thanks!

Monica

**Comment by creepymonster** [comment]
Sorry I'm only getting to this now.

Here is the link
https://testflight.apple.com/join/dWDt5Wme

The link can always be found on the GitHub project page, there is a section called "Quick Test".

**Comment by myanezpagans** [comment]
Dear creepymonster,

Many thanks for your response. I have reviewed the link that you sent to me in detail, but I am afraid I am afraid I am still unsure as to how can I get direct glucose installed in my iPhone. I am able to download the TestFlight app through Apple Store but when I open TestFlight I only get a blank display that says "No Apps Available to test" and the only option to move ahead is to click a Redeem Code.

The link that you shared with me (https://testflight.apple.com/join/dWDt5Wme) suggests two different ways to install direct glucose from TestFlight -- via email or public invitation. But how can I can an invitation email or access to the public invitation. All my apologies if the question/response is too obvious for a non technical person like me this is so difficult to understand.

Many many thanks in advance for your help,


Monica
