### ISSUE TITLE
Import old data

### ISSUE THREAD

**Issue by iMonZ** [creepymonster/GlucoseDirect#436]
Hey,
I use the Libre 3, is it possible to add a feature to import the last weeks of usage from Libre link? Because I just use the app since today and I would love to import my data.

also if this app is closed for a few days, is the data still imported from Libre linkup to health app or is it lost?

**Comment by creepymonster** [comment]
Hello,

thank you very much for the message. Unfortunately, LibreLinkUp does not provide the possibility to get data over a longer period of time. All data (that I get there per request, which is about 12 hours) are imported by me as well.

Many greetings
Reimar
