### ISSUE TITLE
Give warning when you need to accept ToS from Libre Link Up

### ISSUE THREAD

**Issue by AndreasStokholm** [creepymonster/GlucoseDirect#452]
I've been debugging for a while today, and my login didn't work because I needed to accept the ToS of Libre Link Up to get data form my Libre3. It would be awesome if we could get a warning when it's time to re-accept the terms.

The response from the server looks like this when this is the case:

```
{"status":4,"data":{"step":{"type":"pp","componentName":"AcceptDocument","props":{"reaccept":true,"titleKey":"Common.privacyPolicy","type":"pp"}},"user":{"accountType":"pat","country":"SE","uiLanguage":"en-GB"},"authTicket":{"token":"[redacted]","expires":1671406008,"duration":3600000}}}↵

```

**Comment by FokkeZB** [comment]
Instead, I did a PR to automatically accept them: https://github.com/creepymonster/GlucoseDirect/pull/550
