### ISSUE TITLE
[Suggestion] Higher time period over which delta is computed

### ISSUE THREAD

**Issue by niekocaster** [creepymonster/GlucoseDirect#454]
Hi 

Could it be possible to compute the delta over a higher time period such as 5 minutes. With the current 1 minute I feel like there’s missing resolution as it is always +- 0.2 mmol (at least for me) and increasing the time period would give a higher resolution and at least for me a bit more relevant information as the erratic ups and downs don’t always mean anything. 

Love the app the live activity is great! 

Thank you for your time.

**Comment by creepymonster** [comment]
Hello,

thank you very much for the message. The idea is very good. I also think for some time about how I can adjust the "change" useful.

I will note the suggestion and try to consider it after the next update.

Many greetings
Reimar
