### ISSUE TITLE
[Minor bug] Low/high step size

### ISSUE THREAD

**Issue by partcoffee** [creepymonster/GlucoseDirect#492]
Tapping the plus/minus icons to adjust your low/high range adjusts by mg/dL, even if mmol/L is selected. This leads to multiple taps to go from e.g. 6.0 mmol/L to 6.1 mmol/L.

Minor issue, as it's unlikely to be adjusted often.

**Comment by creepymonster** [comment]
Hello,

thanks for the hint. Soon I will replace the sliders with normal input fields.

The problem will no longer occur there, but the basic problem will unfortunately remain. The mmol/L values with 1 decimal place are not accurate enough to display mg/dl.

For example, 79 mg/dl is 4.4 mmol, but so is 80.

Many greetings
Reimar
