### ISSUE TITLE
[Bug] Notifications not mirrored to Apple Watch

### ISSUE THREAD

**Issue by partcoffee** [creepymonster/GlucoseDirect#493]
When you get a high/low glucose notification, it is not mirrored to the Watch, but instead vibrates the phone. This is not consistent with how notifications are handled in other apps, e.g. Messages or Reminders.

Mirroring is controlled in the Watch app itself, so it shouldn't have to be a setting within the app itself.

**Comment by creepymonster** [comment]
Hello,

thank you very much for your message.

I cannot influence where the notifications are delivered (Apple Watch or iPhone).

Here is an article from on the subject:
https://support.apple.com/en-us/HT204791

Many greetings
Reimar
