### ISSUE TITLE
Apple Watch support?

### ISSUE THREAD

**Issue by iDustbin** [creepymonster/GlucoseDirect#519]
Hi, I changed nothing and iOS app reporting working since 2x days. I want to say thank you, your effort was really helpful!! 

One more question, is it possible to include glucose level to Apple Watch ? I would prefer to see it all time as "widget" 

Hope you had an idea

**Comment by Houbsi** [comment]
@iDustbin 

Would be beneficial, when you closed this ticket, that you at least post the solution to your issue :)
