### ISSUE TITLE
Libre 2: unsupported sensor: unknown

### ISSUE THREAD

**Issue by enodr** [creepymonster/GlucoseDirect#549]
Hi,

Using Libre 2 EU sensors. Never had problem before but the last batch of sensors I got are not recognized by the app.

The error message does not give much insight.

How can I help debug? Also curious not seing more reports about this issue. Something changed in the latest sensors ?

**Comment by patriceo** [comment]
Hi @enodr same problem for me. I have been using Libre 2 EU sensors for months without any issues, the latest one gives me the same unsupported sensor issue. 

How can we help?

**Comment by askorza** [comment]
i have same issue

**Comment by enodr** [comment]
I can confirm the fix works perfectly with the new sensors. Marking as closed for me.
