### ISSUE TITLE
Missing User or token after changing the sensor

### ISSUE THREAD

**Issue by AnkeToni** [creepymonster/GlucoseDirect#587]
Hello,
after changing the sensor (Freestyle Libre 3) I get an Error: "Missing user or token".
Before everything works really fine and I was so happy with the app.

I didn't changed anything - only new sensor. LibreView works and has no Bluethooth connection.
Scanning the sensor also does not solve the problem. Scanning is sucessful but still the same error.

What can I else do?

Thanks to all for any hint!

**Comment by gui-dos** [comment]
The last Settings menu item lets you get the file “AllLogs.log”: it is in simple text format so you can paste it here after editing out your sensitive personal data.
